# Generated by Django 2.2.16 on 2022-08-10 07:04

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=255, verbose_name='код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validators.username_value_not_me], verbose_name='Имя пользователя'),
        ),
    ]
